---
- name: install and configure agent2
  hosts: wp
  become: true
  tasks:

    - name: download deb package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release.deb"

    - name: install repo
      command: dpkg -i /tmp/zabbix-release.deb

    - name: apt update
      apt:
        update_cache: yes

    - name: install zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: copy zabbix_agent2.conf
      copy:
        src: ./zabbix_agent2.conf
        dest: /home/ubuntu/zabbix_agent2.conf.tmp

    - name: set hostname in zabbix_agent2.conf.tmp
      lineinfile:
        path: /home/ubuntu/zabbix_agent2.conf.tmp
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"

    - name: change hostname in zabbix_agent2.conf
      ansible.builtin.shell:
        cmd: sed 's/\(Hostname=wp-[0-9]\).r.*.net/\1/;' /home/ubuntu/zabbix_agent2.conf.tmp > /home/ubuntu/zabbix_agent2.conf
        chdir: /home/ubuntu

    - name: copy zabbix config to /etc/zabbix/
      copy:
        remote_src: true
        src: /home/ubuntu/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: "0644"

    - name: chmod 640 /var/log/php8.1-fpm.log
      file:
        path: /var/log/php8.1-fpm.log
        mode: "0640"

    - name: copy default nginx
      copy:
        src: ./default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0777"

    - name: add zabbix to the root group # it is not for production though
      user:
        name: zabbix
        groups: "root, adm"
        append: yes

    - name: restart zabbix, nginx
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - zabbix-agent2
        - nginx
